const answers = ["I am haunted by feedback",
  "Acceptance criteria",
  "Kanban",
  "Daily Dance-Up",
  "Feedback",
  "Goldratt",
  "The Burndown",
  "Sprint Planning that lasts 8 hours",
  "A ScrumMaster's Ghost",
  "Scrum",
  "full-stack COBOL Developer",
  "Essentiall SAFe",
  "Boris Glogger",
  "Big Room Planning",
  "high-performance team",
  "we are now doing PO-stories",
  "we test in the next sprint",
  "Cost rising",
  "hangover",
  "changing the sprint length",
  "Martin Fowler",
  "Jeff Sutherland",
  "we will give 110%",
  "it's not my job",
  "Bavarian native speaker",
  "chocolate",
  "testing is in Ukraine",
  "a retrospective with only the ScrumMaster",
  "team members in India",
  "marshmallow",
  "middle management",
  "hugs",
  "hugging",
  "the Traditional Project Manager a.k.a. ScrumMaster",
  "HR Department",
  "a task force",
  "The CEO",
  "Continuous delivery",
  "a micromanaging PO",
  "on-site customer",
  "waterfall extremist",
  "1:1s",
  "why not?",
  "20-person scrum team",
  "waerfall-scrum-fall",
  "deadline",
  "extended the sprint",
  "kanban without WIP-Limits",
  "2-hour long Daily Scrum",
  "Agile annual budget",
  "project",
  "ask the Team",
  "ask the PO",
  "ask the ScrumMaster",
  "ask the Project Manager",
  "backlog written on one post-it",
  "a pile of horse-$xxt user-storiies",
  "let's switch to Nexus",
  "skipping the Retrospective",
  "the drinking Finns",
  "getting input",
  "T-shirt sizes",
  "broken CD pipeline",
  "just close it",
  "planning poker",
  "team charter",
  "working agreements",
  "sobriety",
  "scrum of scrums",
  "human emotions",
  "broken-hearted POs",
  "tasty cupcakes",
  "drunken ScrumMaster",
  "information radiator",
  "we are stuck in the sauna",
  "nasty retrospectives",
  "continuous delivery of beer",
  "grab them by the sticky",
  "write on whiteboard with permanent marker",
  "Denning",
  "the deep-freeze",
  "we can't put things on the wall",
  "resistance",
  "dreaming of waterfall",
  "release-train engineer",
  "licking post-its' backside",
  "I want to feel SAFe",
  "scaliing head-count",
  "because we were told",
  "the ScrumMaster decided",
  "Product Backlog",
  "ScrumMaster from hell",
  "a neck-tie delivering 50000 volts",
  "yearly roadmap planning meeting",
  "Agile Manifesto",
  "we have a separate backlog for that",
  "we'll use stickies",
  "definition of fun",
  "twice the work for half the time",
  "a horny ScrumMaster",
  "it's just a forecast",
  "refactoring",
  "values and principles",
  "hours",
  "story-points",
  "meetings",
  "lying",
  "Polish team members",
  "the scientific method",
  "promiscuous pair-programming",
  "theory of constraints",
  "death march",
  "coaching",
  "confluence",
  "wikipedia",
  "the Big Bang agile transformation",
  "the newbie",
  "thrown it over the wall",
  "ScrumMaster",
  "break the build",
  "sharpies",
  "a bus-factor of 1",
  "agile games",
  "burndown",
  "thin air",
  "process agility",
  "pretend Scrum",
  "Agile Steerinng Group",
  "lying in Daily Scrum",
  "diversity",
  "un-shippable product decrement",
  "pigs & chickens",
  "story cubes",
  "having Daily Scrum in the pool",
  "insect & adapt",
  "getting verbally abused",
  "eXtreme whining",
  "an action item",
  "the login process",
  "the silent Swede",
  "the cocktail napkins",
  "blanks",
  "Lift-off",
  "estimate in man-days",
  "debug in production",
  "team work",
  "requirements document",
  "coding while sober",
  "Craig Larman",
  "love",
  "a feature toggle",
  "a serial-killer persona",
  "personal coaching",
  "it's not a bug, it's a feature",
  "we moved to the cloud",
  "buggy feature",
  "burndown paper",
  "it must be SAFe",
  "empty backlog",
  "showcase your rebel self",
  "the Kruger Dunning Effect",
  "theres not enough budget",
  "set the build-indicator to grey-scale",
  "kudo-cards",
  "you're doing it wrong",
  "the user is wrong",
  "Lego bricks",
  "put it on the sticky",
  "failure",
  "ownership culture",
  "compassion",
  "using a voodoo doll",
  "Sprint Planning",
  "documentation",
  "Planning Sprint",
  "bugs",
  "DevOps",
  "pair-programming",
  "my team",
  "ITIL",
  "PMI",
  "Prince2",
  "a burndown gone up",
  "we changed the customer's requirements",
  "we changed the acceptance criteria",
  "we changed the DoD",
  "team without a board",
  "missing the release train",
  "not in the budget",
  "sprint",
  "naked User Stories",
  "random story-point generator",
  "feature",
  "remote team-member",
  "pairing",
  "DSDM",
  "CSM training",
  "a column on the task-board",
  "retro by video ",
  "a dead ScrumMaster",
  "disable the tests",
  "Deming",
  "the architects",
  "Scrum",
  "our DoD",
  "visual facilitation",
  "marshmallow challenge",
  "failed sprint",
  "the Penny Game",
  "a Jira ticket",
  "absent Product Owner",
  "Agile Project Manager",
  "Jira",
  "it works on my machine",
  "cost cuts",
  "sitting on the toilet during Daily Scrum",
  "a hitting stick",
  "not giving a $h*t about other team members",
  "Technical Debt",
  "touching the women in Daily Scrum",
  "the talkative Italian",
  "a pile of sh*t",
  "allergy to sticky notes",
  "remove it from the sprint",
  "#NoEstimates!",
  "retro retrospectives",
  "team play",
  "the customer won't pay for this",
  "feelings retro",
  "code review",
  "we broke the sprint",
  "automation",
  "because we are agile",
  "powerful questions",
  "Mike Cohn",
  "grab them by the story points",
  "usability",
  "burndown the house",
  "the process",
  "disordered backlog",
  "cowboy coding",
  "Cynefin",
  "minimum viable product",
  "done-done",
  "fake scrum",
  "play with Lego bricks",
  "shu-ha-ri",
  "mob-programming",
  "post-its",
  "fake portfolio management",
  "a sexy ScrumMaster's butt",
  "Sprint Zero",
  "certification",
  "can you do me a small favour",
  "swimlanes",
  "PSPI - potentially shippable product increment",
  "write a test",
  "User Acceptance Testing (UAT)",
  "Agile virus injections",
  "this is how we do it",
  "commitment",
  "licking user-stories cards to claim them as your own",
  "we don't do documentation",
  "sprint goal",
  "a team-full of men",
  "happy testers",
  "Scrummerfall",
  "craftsman",
  "there is a lot of licking",
  "project manager as a ScrumMaster",
  "dot-voting",
  "tummy-ache",
  "group dynamic",
  "retrospective",
  "mocking the ScrumMaster",
  "wome in short skirts",
  "a pile of former ScrumMasters' heads",
  "the ScrumMaster whip",
  "ScrumBan",
  "seeing the PO naked",
  "whip-limits",
  "pre-mortem",
  "the daily mosh-pit",
  "the one female team-member",
  "a micro-manager's wet dream",
  "backlog refinement",
  "Agile song contest",
  "hardening sprint",
  "our CFD",
  "it's an experiment",
  "Sprint goal",
  "hierarchy",
  "timebox",
  "LeSS",
  "the CEO said so",
  "the SM decides",
  "the customer",
  "an ivory tower",
  "smelly team member",
  "The Change Manager",
  "the German Chancellor",
  "authentication",
  "the sauna",
  "write it on a post-it",
  "remove it from the demo",
  "conferences",
  "comment out the text",
  "put it in production NOW",
  "this is waste",
  "we've always done it that way",
  "coding standards",
  "prototyping",
  "split it",
  "we do standups",
  "put it on the wiki",
  "home-office",
  "Kaizen",
  "no vision",
  "gin and tonic",
  "stale beer",
  "impediments",
  "real coders test in production",
  "scaling",
]

const questions = [
  "This is the way the world ends. Not with a bang but with ---.",
  "Dear Abby, I'm having some trouble with --- and would like your advice.",
  "Kids, I don't need drugs to get high. I'm high on ---",
  "I'm sorry sir, but I couldn't complete my homework because of ---",
  "Well, if you'll excuse me, gentlemen, I have a date with ---",
  "A recent laboratory study shows that undergraduates have 50 % less sex after being exposed to ---",
  "  Why can't I sleep at night? ---",
  // "I never trully understood --- until I encountered ----.",
  // "In a world ravaged by --- our only solace is ----.",
  "Maybe she's born with it. Maybe it's ---",
  "  It's a pitty that kids these days are all getting involved with --- ",
  // "Introducing the amazing Superhero / Sidekick duo! It's ---  and ----",
  // "They said we were crazy.They said we could not put --- inside of ---.They were vwrong!",
  "What ended my last relationship? ---",
  "---? Jim will fix it!",
  "I got 99 problems, but --- ain't one.",
  "Why do i hurt all over? ---",
  "What's that sound? --- ",
  "I drink to forget ---.",
  // "Step 1: --- Step 2: ---- Step 3: Profit",
  "The theme for next year's Eurovision Song Contest is 'We are ---'",
  "--- good to the last drop.",
  // "For my next trick I will pull --- out of----",
  "How am I maintaining my relationship status? ---",
  "War! What is it good for? ---",
  "Why am I sticky? ---",
  "What's my secret power? ---",
  "What did I brring back from Amsterdam? ---",
  "Airport security guidelines now prohibit --- on airplanes.",
  // "--- is a slippery slope that leads to ----",
  "A romantic candle - lit dinner would be incomplete without ---",
  // "--- +  ----  = -----",
  "The customer wants ---",
  "We need to automate ---",
  "Every team should have ---",
  "--- will help us achieve our business goals",
  "We have always done ---",
  "Don't show --- in the review!",
  "--- really turns me on!",
  "We tried --- already, and it does not work.",
  "--- was not in the contract",
]

module.exports = {
  answers,
  questions
}